# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b087799c00db4eb256680ce4252c1ebf277d26aa68f8cab5cac79fb7ce677d523975d90078b645ba77a046c11d8931b930cd111fd45b2240f6d14b7edbd15dd

test:
  secret_key_base: 591975fd5a6698266215bb3f196bea52db64448b760925bf3882a86fc77532c505f7baa6cbe5a540488f6bb3d375a74f4e7043864d59d6f6d85459badfd92b78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
